### ISSUE TITLE
Subscriber issue 

### ISSUE THREAD

**Issue by ravikasyap1717** [myDevicesIoT/Cayenne-MQTT-CPP#1]
Hi, 
I am running subscribe example.But I am not able to get any output in console.

For subscribe, i am using DATA_TOPIC.
if (message.topic == DATA_TOPIC) {
		mqttClient.publishResponse(message.id, NULL, message.clientID);
	}
and 
mqttClient.subscribe(DATA_TOPIC, CAYENNE_NO_CHANNEL);

int main(int argc, char** argv)
{
	// Set the default function that receives Cayenne messages.
		mqttClient.setDefaultMessageHandler(messageArrived);

	// Connect to Cayenne.
	if (connectClient() == CAYENNE_SUCCESS) {
		// Run main loop.
		loop();
	}
	else {
		printf("Connection failed, exiting\n");
	}

	return 0;
}
I am able to publish data on this topic.
mqttClient.publishData(DATA_TOPIC, CAYENNE_NO_CHANNEL, NULL, NULL, Message);

Please let me know,where am i doing wrong.How can i fix this issue.

**Comment by jburhenn** [comment]
`DATA_TOPIC` should be published to a specific channel. So instead of `CAYENNE_NO_CHANNEL` you would use a channel number. Also if you are trying to subscribe to get widget data from Cayenne you should use `COMMAND_TOPIC` instead of `DATA_TOPIC`. The `publishResponse()` function is for responding to command messages, not data messages.

So, to clarify, `DATA_TOPIC` should be used for sending data to to Cayenne and `COMMAND_TOPIC` should be used for receiving command messages from Cayenne. Further info about topics is here: http://www.cayenne-mydevices.com/docs/#bring-your-own-thing-api-mqtt-messaging-topics

And info about using the Cayenne C++ library is available here: http://www.cayenne-mydevices.com/docs/#bring-your-own-thing-api-using-c

**Comment by ravikasyap1717** [comment]
Hi, Thanks for reply.
I want to use this library for my local host.If i am checking in broker utility on Topic "data" and publish my message, i am able to see my message.But when i am trying to subscribe on channel 1.I am not getting any message.So, let me know can we use this library for own broker ?

**Comment by jburhenn** [comment]
Yes, this library should work with your own broker. If you need it to subscribe to `DATA_TOPIC` payloads you can uncomment the `PARSE_INFO_PAYLOADS` define in `CayenneDefines.h`. That should compile in code for handling data topic messages.
